using System.IO;
using System.Reflection;
using System.Windows.Media.Imaging;

namespace CodeCompliance
{
    /// <summary>
    /// Loads the APG brand icons embedded in the assembly (src/CodeCompliance/Resources).
    /// Icons are regenerated by tools/gen-icons.ps1; embedded resource names follow the
    /// pattern "CodeCompliance.Resources.&lt;Name&gt;.png".
    /// </summary>
    internal static class RibbonIcons
    {
        public static BitmapImage? Get(string name)
        {
            Stream? stream = Assembly.GetExecutingAssembly()
                .GetManifestResourceStream("CodeCompliance.Resources." + name + ".png");
            if (stream == null)
                return null;

            var image = new BitmapImage();
            image.BeginInit();
            image.CacheOption = BitmapCacheOption.OnLoad;
            image.StreamSource = stream;
            image.EndInit();
            image.Freeze();
            return image;
        }
    }
}
