using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using Autodesk.Revit.DB;

namespace CodeCompliance.Core.Dm
{
    /// <summary>Outcome of binding the DM shared parameters to the model.</summary>
    public sealed class DmBindResult
    {
        public int Created { get; set; }
        public int Extended { get; set; }
        public int AlreadyBound { get; set; }
        public int Failed { get; set; }
        public string FilePath { get; set; } = "";
        public List<string> Messages { get; } = new List<string>();

        public string Summary =>
            Created + " parameter(s) bound, " + Extended + " extended to more categories, " +
            AlreadyBound + " already correct" + (Failed > 0 ? ", " + Failed + " failed" : "") + ".";
    }

    /// <summary>
    /// The DM shared parameters, generated from the knowledge base instead of asking the user
    /// for Dubai Municipality's shared parameter file: the plugin writes a valid Revit shared
    /// parameter file itself and can bind every attribute the audit needs to the categories
    /// that need it.
    ///
    /// GUIDs are derived from the parameter name, so the same parameter always gets the same
    /// GUID on every machine and every re-run. If the office already works with DM's official
    /// file, load that file first: existing definitions with the same name are reused and only
    /// the missing ones are created from here.
    /// </summary>
    public static class DmSharedParameters
    {
        /// <summary>Parameter group inside the generated shared parameter file.</summary>
        public const string GroupName = "Building Permit";

        public static string FilePath =>
            Path.Combine(DmKnowledgeBase.OverrideFolder, "DM_SharedParameters.txt");

        /// <summary>
        /// Writes (or refreshes) the shared parameter file containing every DM attribute and
        /// returns its path.
        /// </summary>
        public static string WriteFile()
        {
            Directory.CreateDirectory(DmKnowledgeBase.OverrideFolder);

            var sb = new StringBuilder();
            sb.AppendLine("# This is a Revit shared parameter file.");
            sb.AppendLine("# Generated by APG Revit Plugins – DM BIM Compliance from the Dubai");
            sb.AppendLine("# Municipality attribute data set (Dubai BIM Standard " +
                          DmKnowledgeBase.StandardVersion + ").");
            sb.AppendLine("*META\tVERSION\tMINVERSION");
            sb.AppendLine("META\t2\t1");
            sb.AppendLine("*GROUP\tID\tNAME");
            sb.AppendLine("GROUP\t1\t" + GroupName);
            sb.AppendLine("*PARAM\tGUID\tNAME\tDATATYPE\tDATACATEGORY\tGROUP\tVISIBLE\tDESCRIPTION\tUSERMODIFIABLE\tHIDEWHENNOVALUE");

            foreach (KeyValuePair<string, string> parameter in DmKnowledgeBase.SharedParameters
                         .OrderBy(p => p.Key, StringComparer.OrdinalIgnoreCase))
            {
                sb.AppendLine("PARAM\t" + GuidFor(parameter.Key).ToString() + "\t" + parameter.Key + "\t" +
                              DataType(parameter.Value) + "\t\t1\t1\t\t1\t0");
            }

            File.WriteAllText(FilePath, sb.ToString(), Encoding.UTF8);
            return FilePath;
        }

        /// <summary>Stable, name-derived GUID so re-runs and other machines agree.</summary>
        public static Guid GuidFor(string parameterName)
        {
            using (MD5 md5 = MD5.Create())
            {
                byte[] hash = md5.ComputeHash(Encoding.UTF8.GetBytes("APG-DM-BIM-" + parameterName));
                return new Guid(hash);
            }
        }

        /// <summary>DM data type to the token a Revit shared parameter file uses.</summary>
        public static string DataType(string dmDataType)
        {
            switch ((dmDataType ?? "").ToUpperInvariant())
            {
                case "YESNO": return "YESNO";
                case "INTEGER": return "INTEGER";
                case "NUMBER": return "NUMBER";
                case "LENGTH": return "LENGTH";
                case "AREA": return "AREA";
                case "ANGLE": return "ANGLE";
                case "MASS_DENSITY": return "MASS_DENSITY";
                case "MULTILINETEXT": return "MULTILINETEXT";
                default: return "TEXT";
            }
        }

        /// <summary>
        /// Every attribute the audit needs, with the categories it has to be bound to. Built
        /// from the Appendix B tables of the element rules plus the project, level and room
        /// level attributes.
        /// </summary>
        public static Dictionary<string, List<BuiltInCategory>> RequiredBindings(
            DmPermitStage stage, bool includeConditional)
        {
            var map = new Dictionary<string, List<BuiltInCategory>>(StringComparer.OrdinalIgnoreCase);

            void AddRange(IEnumerable<string> names, params BuiltInCategory[] categories)
            {
                foreach (string name in names)
                {
                    if (string.IsNullOrWhiteSpace(name) || !DmKnowledgeBase.SharedParameters.ContainsKey(name))
                        continue;
                    if (!map.TryGetValue(name, out List<BuiltInCategory>? list))
                    {
                        list = new List<BuiltInCategory>();
                        map[name] = list;
                    }
                    foreach (BuiltInCategory category in categories)
                    {
                        if (!list.Contains(category))
                            list.Add(category);
                    }
                }
            }

            IEnumerable<string> Table(string table)
            {
                return DmKnowledgeBase.RequiredAttributes(table, stage, includeConditional)
                    .Where(a => a.UserInput)
                    .Select(a => a.Name);
            }

            IEnumerable<string> Ids(string entity)
            {
                return DmKnowledgeBase.IdsPropertiesFor(entity).Select(r => r.BaseName);
            }

            // Project / site / building.
            AddRange(Table("Project"), BuiltInCategory.OST_ProjectInformation);
            AddRange(Table("Building"), BuiltInCategory.OST_ProjectInformation);
            AddRange(Table("Topography_Site"), BuiltInCategory.OST_ProjectInformation);
            AddRange(Ids("IFCPROJECT"), BuiltInCategory.OST_ProjectInformation);
            AddRange(Ids("IFCSITE"), BuiltInCategory.OST_ProjectInformation);
            AddRange(Ids("IFCBUILDING"), BuiltInCategory.OST_ProjectInformation);

            // Levels.
            AddRange(Table("Storey"), BuiltInCategory.OST_Levels);
            AddRange(Ids("IFCBUILDINGSTOREY"), BuiltInCategory.OST_Levels);

            // Rooms and parking.
            AddRange(Table("Room_Spaces"), BuiltInCategory.OST_Rooms);
            AddRange(Ids("IFCSPACE"), BuiltInCategory.OST_Rooms);
            AddRange(Table("Parking_Spaces"), BuiltInCategory.OST_Rooms, BuiltInCategory.OST_Parking);

            // Model elements.
            foreach (DmElementRule rule in DmRuleCatalog.ElementRules)
            {
                AddRange(Table(rule.Table), rule.Categories);
                AddRange(Ids(rule.IfcEntity), rule.Categories);
            }

            return map;
        }

        /// <summary>
        /// Creates the missing DM shared parameters and binds them to their categories.
        /// Must be called inside an open transaction.
        /// </summary>
        public static DmBindResult Bind(Document doc, Dictionary<string, List<BuiltInCategory>> bindings)
        {
            var result = new DmBindResult { FilePath = WriteFile() };

            Autodesk.Revit.ApplicationServices.Application app = doc.Application;
            string previousFile = app.SharedParametersFilename;
            try
            {
                app.SharedParametersFilename = result.FilePath;
                DefinitionFile file = app.OpenSharedParameterFile();
                if (file == null)
                {
                    result.Messages.Add("Revit could not open the generated shared parameter file.");
                    return result;
                }

                DefinitionGroup? group = file.Groups.get_Item(GroupName);
                if (group == null)
                {
                    result.Messages.Add("The generated shared parameter file has no \"" + GroupName + "\" group.");
                    return result;
                }

                Categories categories = doc.Settings.Categories;
                BindingMap bindingMap = doc.ParameterBindings;

                foreach (KeyValuePair<string, List<BuiltInCategory>> entry in bindings)
                {
                    try
                    {
                        var definition = group.Definitions.get_Item(entry.Key) as ExternalDefinition;
                        if (definition == null)
                        {
                            result.Failed++;
                            continue;
                        }

                        var wanted = new List<Category>();
                        foreach (BuiltInCategory builtIn in entry.Value)
                        {
                            Category? category = SafeCategory(categories, builtIn);
                            if (category != null && category.AllowsBoundParameters)
                                wanted.Add(category);
                        }
                        if (wanted.Count == 0)
                            continue;

                        var existing = bindingMap.get_Item(definition) as ElementBinding;
                        if (existing == null)
                        {
                            CategorySet set = app.Create.NewCategorySet();
                            foreach (Category category in wanted)
                                set.Insert(category);
                            if (bindingMap.Insert(definition, app.Create.NewInstanceBinding(set), GroupTypeId.Data))
                                result.Created++;
                            else
                                result.Failed++;
                            continue;
                        }

                        var missing = wanted
                            .Where(c => !existing.Categories.Contains(c))
                            .ToList();
                        if (missing.Count == 0)
                        {
                            result.AlreadyBound++;
                            continue;
                        }

                        CategorySet merged = app.Create.NewCategorySet();
                        foreach (Category category in existing.Categories.Cast<Category>())
                            merged.Insert(category);
                        foreach (Category category in missing)
                            merged.Insert(category);

                        if (bindingMap.ReInsert(definition, app.Create.NewInstanceBinding(merged), GroupTypeId.Data))
                            result.Extended++;
                        else
                            result.Failed++;
                    }
                    catch (Exception ex)
                    {
                        result.Failed++;
                        if (result.Messages.Count < 5)
                            result.Messages.Add(entry.Key + ": " + ex.Message);
                    }
                }
            }
            finally
            {
                try
                {
                    if (!string.IsNullOrEmpty(previousFile))
                        app.SharedParametersFilename = previousFile;
                }
                catch
                {
                    // restoring the user's own shared parameter file is best effort
                }
            }

            return result;
        }

        private static Category? SafeCategory(Categories categories, BuiltInCategory builtIn)
        {
            try
            {
                return categories.get_Item(builtIn);
            }
            catch
            {
                return null;
            }
        }
    }
}
